TRACKER_LIB_REL_DIR := $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))

C_SOURCES_TRACKER += $(TRACKER_LIB_REL_DIR)/tracker.c
C_SOURCES_TRACKER += $(TRACKER_LIB_REL_DIR)/kf.c

C_INCLUDES_TRACKER += -I$(TRACKER_LIB_REL_DIR)

C_DEFS_TRACKER += -DTRACKER_MODULE

C_SOURCES += $(C_SOURCES_TRACKER)
C_INCLUDES += $(C_INCLUDES_TRACKER)
C_DEFS += $(C_DEFS_TRACKER)

foo:
	@echo $(TRACKER_LIB_REL_DIR)
